In [16]:
import numpy as np

arr = np.array([[1, 2, 3],[4, 5, 6]])

print(np.sum(arr))

print(np.sum(arr, axis=0))

print(np.sum(arr, axis=1))

21
[5 7 9]
[ 6 15]


##### 2D

##### 3D

In [17]:
arr = np.array([[[1, 2, 3],
                [4, 5, 6]],
                [[7, 8, 9],
                [10, 11, 12]]])

print(np.sum(arr, axis=0))
print()
print(np.sum(arr, axis=1))
print()
print(np.sum(arr, axis=2))

[[ 8 10 12]
 [14 16 18]]

[[ 5  7  9]
 [17 19 21]]

[[ 6 15]
 [24 33]]


In [27]:
np.shape(arr)
print()
print(np.reshape(arr, (2, 3, 2)))
print(np.ndim(arr))


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [29]:
print(arr.T)

[[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]


In [33]:
#print(arr ** 2)
sq = arr ** 2

print(sq)

[[[  1   4   9]
  [ 16  25  36]]

 [[ 49  64  81]
  [100 121 144]]]


##### mathematical operators

In [38]:
print(np.exp(sq))

[[[2.71828183e+00 5.45981500e+01 8.10308393e+03]
  [8.88611052e+06 7.20048993e+10 4.31123155e+15]]

 [[1.90734657e+21 6.23514908e+27 1.50609731e+35]
  [2.68811714e+43 3.54513118e+52 3.45466066e+62]]]


In [51]:
print(np.round(np.log(sq), 2))

[[[0.   1.39 2.2 ]
  [2.77 3.22 3.58]]

 [[3.89 4.16 4.39]
  [4.61 4.8  4.97]]]


In [46]:
print(np.sqrt(sq).astype(int))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
arr_three = np.array([[[1, 2, 3],
                [4, 5, -6]],
                [[7, 8, 9],
                [-10, 11, 12]]])

absolute = np.abs(arr_three)

print(np.array(absolute[1,1,:]))

print(np.where(absolute > 8, 0, 1))

print()

print(arr_three[0])

print(arr_three[0,1,0])

[10 11 12]
[[[1 1 1]
  [1 1 1]]

 [[1 1 0]
  [0 0 0]]]

[[ 1  2  3]
 [ 4  5 -6]]
4


##### Brocasting

In [ ]:
a = np.array([[10, 20, 30], 
              [40, 50, 60], 
              [70, 80, 90]])

print(a[0:2,0:2])
print()

print(a[1:,1:])
print()

print(a.size)
print(a.shape)
print(a.ndim)



[[10 20]
 [40 50]]

[[50 60]
 [80 90]]

9
(3, 3)
2
[10 20 30]


In [89]:
py_list = np.array([1, 2, 3, 4, 5])

sub = py_list[1:3].copy()

sub[0] = 999

print(py_list)
print()
print(sub)

[1 2 3 4 5]

[999   3]


In [102]:
print(np.arange(24).reshape(2,3,4).shape)

(2, 3, 4)


In [ ]:
import pandas as pd

s = pd.Series([10, 20, None, 30],index = ["A","B","C","D"])

print(s.index)

print(s.values)

np.dtype(s)

Index(['A', 'B', 'C', 'D'], dtype='object')
[10. 20. nan 30.]


dtype('float64')